using System.Text.Json;
using WriteLite.AI.Local;

namespace WriteLite.Tests.Ai;

/// <summary>
/// Checks the C# tokenizer against frozen HuggingFace output.
/// </summary>
/// <remarks>
/// A tokenizer mismatch is the quietest way to break a fine-tuned model: the
/// session still runs, the logits still look like probabilities, and every
/// score is subtly wrong because the model is seeing a segmentation it never
/// trained on. The fixture is regenerated by
/// <c>ai/scripts/export_tokenizer_fixture.py</c>.
/// </remarks>
[TestClass]
public sealed class WordPieceTokenizerTests
{
    private static string FixturePath => Path.Combine(AppContext.BaseDirectory, "Fixtures", "tokenizer-reference.json");
    private static string VocabPath => ResolveVocab();

    private static string ResolveVocab()
    {
        foreach (var candidate in new[]
                 {
                     Path.Combine(AppContext.BaseDirectory, "models", "writelight-reranker", "vocab.txt"),
                     Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "models", "writelight-reranker", "vocab.txt")),
                     Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "ai", "models", "rubert-tiny2", "vocab.txt")),
                 })
        {
            if (File.Exists(candidate)) return candidate;
        }

        return string.Empty;
    }

    [TestMethod]
    public void Segmentation_MatchesTheReferenceTokenizer()
    {
        if (!File.Exists(FixturePath) || VocabPath.Length == 0)
        {
            Assert.Inconclusive("tokenizer fixture or vocabulary not deployed");
            return;
        }

        using var document = JsonDocument.Parse(File.ReadAllText(FixturePath));
        var root = document.RootElement;
        var maxLength = root.GetProperty("maxLength").GetInt32();
        var lowercase = root.GetProperty("lowercase").GetBoolean();

        var tokenizer = WordPieceTokenizer.LoadFromVocabFile(VocabPath, lowercase);
        Assert.IsNotNull(tokenizer);

        var special = root.GetProperty("specialTokens");
        Assert.AreEqual(special.GetProperty("cls").GetInt32(), tokenizer.ClsId, "[CLS] id");
        Assert.AreEqual(special.GetProperty("sep").GetInt32(), tokenizer.SepId, "[SEP] id");
        Assert.AreEqual(special.GetProperty("pad").GetInt32(), tokenizer.PadId, "[PAD] id");
        Assert.AreEqual(special.GetProperty("unk").GetInt32(), tokenizer.UnknownId, "[UNK] id");

        var mismatches = new List<string>();
        foreach (var testCase in root.GetProperty("cases").EnumerateArray())
        {
            var text = testCase.GetProperty("text").GetString()!;
            var expected = testCase.GetProperty("inputIds").EnumerateArray().Select(e => e.GetInt32()).ToArray();
            var actual = tokenizer.Encode(text, maxLength).InputIds;

            if (!expected.SequenceEqual(actual))
            {
                var firstDifference = Enumerable.Range(0, Math.Min(expected.Length, actual.Length))
                    .FirstOrDefault(i => expected[i] != actual[i], -1);
                mismatches.Add($"{text} (first difference at {firstDifference})");
            }
        }

        Assert.AreEqual(0, mismatches.Count,
            "tokenization diverged from the reference for: " + string.Join("; ", mismatches));
    }

    [TestMethod]
    public void UnknownScript_FallsBackToTheUnknownToken()
    {
        if (VocabPath.Length == 0)
        {
            Assert.Inconclusive("vocabulary not deployed");
            return;
        }

        var tokenizer = WordPieceTokenizer.LoadFromVocabFile(VocabPath, lowercase: false)!;
        var ids = tokenizer.Tokenize("\U0001F600\U0001F600\U0001F600").ToArray();
        Assert.IsTrue(ids.Length > 0);
        Assert.IsTrue(ids.All(id => id == tokenizer.UnknownId || id >= 0));
    }
}
