<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>candcov</AssemblyName>
    <RootNamespace>CandCov</RootNamespace>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\shared\Classify.cs" Link="Classify.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WriteLite.App\WriteLite.App.csproj" />
  </ItemGroup>
</Project>
